<?php
$z[0]=Array("arclist","\n\n[field:pubdate function=strftime('%Y-%m-%d',@me)/]\n\n",157,274);
$z[0][4]=array();
$z[0][4]['row']="1";
$z[0][4]['titlelen']="24";
$z[0][4]['orderby']="pubdate";
$z[1]=Array("channel","\n\n<url>\n\n<loc>http://www.yuyafulishu.com[field:typelink /]</loc>\n\n<changefreq>daily</changefreq>\n\n<priority>0.8</priority>\n\n</url>\n\n",352,533);
$z[1][4]=array();
$z[1][4]['row']="23";
$z[1][4]['type']="top";
$z[2]=Array("arclist","\n\n<url>\n\n<loc>http://www.yuyafulishu.com[field:arcurl/]</loc>\n\n<lastmod>[field:pubdate function=strftime('%Y-%m-%d',@me)/]\n\n</lastmod>\n\n<changefreq>monthly</changefreq>\n\n</url>\n\n",535,767);
$z[2][4]=array();
$z[2][4]['row']="2000";
$z[2][4]['orderby']="pubdate";

?>